name: hoc24
description: A Flutter Clean Architecture Using GetX.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2
  animated_notch_bottom_bar: ^1.0.3
  carousel_slider: ^5.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_animate: ^4.2.0+1
  timelines: ^0.1.0
  auto_size_text: ^3.0.0
  badges: ^3.1.2

  # Get
  get: ^4.6.6

  # Image
  cached_network_image: ^3.3.1

  # Local Storage
  shared_preferences: ^2.2.3
  get_storage: ^2.1.1

  # API
  http: ^1.2.1
  dio: ^5.4.3+1
  graphql_flutter: ^5.1.2

  # Login
  google_sign_in: ^6.2.1

  # Webview
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
#  webview_flutter:
#    git:
#      url: https://github.com/libo1223/plugins.git
#      path: packages/webview_flutter

  # Localization
  intl: any
  timeago: ^3.6.1
  flutter_keyboard_visibility: ^5.4.1

  # Fonts and Icons
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1

  # Config
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  # AdMod
  google_mobile_ads: ^5.1.0

  # Cryptographic
  crypto: ^3.0.3

  # File
  file_picker: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  build_runner: ^2.4.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true
  web: false

  android_12:
    color: "#ffffff"
    color_dark: "#ffffff"
    image: assets/images/splash.png

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/subjects/
    - assets/data/
    - assets/svg/
    - assets/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
